[package]
name = "bitcoincore-rpc"
version = "0.8.0-rc1"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>"
]
license = "CC0-1.0"
homepage = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc/"
repository = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc/"
description = "RPC client library for the Bitcoin Core JSON-RPC API."
keywords = [ "crypto", "bitcoin", "bitcoin-core", "rpc" ]
readme = "README.md"

[lib]
name = "bitcoincore_rpc"
path = "src/lib.rs"

[dependencies]
bitcoincore-rpc-json = { version = "0.8.0-rc1", path = "../json" }

log = "0.4.5"
jsonrpc = "0.11"

# Used for deserialization of JSON.
serde = "1"
serde_json = "1"
hex = "0.3"

# Used for Bitcoin-specific types.
bitcoin = { version = "0.19.1", features = [ "use-serde" ] }
num-bigint = { version = "0.2", features = [ "serde" ] }
