[package]
name = "bitcoinsv-rpc"
version = "0.19.0"
authors = [
    "Daniel Connolly <daniel@dconnolly.com>"
]
license = "Open BSV"
homepage = "https://github.com/Danconnolly/rust-bitcoinsv-rpc/"
repository = "https://github.com/Danconnolly/rust-bitcoinsv-rpc/"
description = "RPC client library for the Bitcoin SV JSON-RPC API."
keywords = ["crypto", "bitcoin", "bitcoin-sv", "rpc"]
readme = "README.md"
edition = "2021"

[lib]
name = "bitcoinsv_rpc"
path = "src/lib.rs"

[dependencies]
bitcoinsv-rpc-json = { version = "0.19.0", path = "../json" }
log = "0.4.5"
jsonrpc = "0.16.0"
serde = "1"
serde_json = "1"
sv = "0.2.2"
hex = "0.4.3"

[dev-dependencies]
tempfile = "3.3.0"

