[workspace]
resolver = "2"
members = [
    "json",
    "client",
    "integration_test",
]

[workspace.dependencies]
bitcoinsv = { git = "https://github.com/Danconnolly/rust-bitcoinsv.git", features = ["dev_tokio"] }

