[package]
name = "integration_test"
version = "0.1.0"
authors = ["Steven Roose <steven@stevenroose.org>"]
edition = "2021"

[dependencies]
dashcore-rpc = { path = "../client" }
lazy_static = "1.4.0"
log = "0.4"
hex = "0.4.3"
dotenvy = "0.15.7"
