[package]
name = "integration_test"
version = "0.1.0"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
edition = "2021"

[dependencies]
bitcoinsv-rpc = { path = "../client" }
lazy_static = "1.4.0"
log = "0.4"
env_logger = "0.10.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
