[package]
name = "integration_test"
version = "0.1.0"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
edition = "2018"

[dependencies]
bitcoinsv-rpc = { path = "../client" }
bitcoin = { version = "0.31.0", features = ["serde", "rand"]}
lazy_static = "1.4.0"
log = "0.4"
