[package]
name = "integration_test"
version = "0.1.0"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
edition = "2021"

[dependencies]
bitcoinsv-rpc = { path = "../client" }
sv = "0.2.2"
lazy_static = "1.4.0"
log = "0.4"
