[package]
name = "integration_test"
version = "1.0.2"
authors = ["Daniel Connolly <daniel@dconnolly.com>"]
edition = "2021"

[dependencies]
bitcoinsv = { workspace = true }
bitcoinsv-rpc = { path = "../client" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

