[package]
name = "bitcoinsv-rpc-json"
version = "0.19.0"
authors = [
    "Daniel Connolly <daniel@dconnolly.com>"
]
license = "Open BSV"
homepage = "https://github.com/Danconnolly/rust-bitcoinsv-rpc/"
repository = "https://github.com/Danconnolly/rust-bitcoinsv-rpc/"
description = "JSON-enabled type structs for bitcoinsv-rpc crate."
keywords = [ "crypto", "bitcoin", "bitcoin-sv", "rpc" ]
readme = "README.md"
edition = "2018"

[lib]
name = "bitcoinsv_rpc_json"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

bitcoin = { version = "0.31.0", features = ["serde", "rand-std"]}
